###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
image:
  repository: ibmcom/mq
  tag: 9
service:
  name: qmgr
  type: ClusterIP
resources:
  storage:
    size: 2Gi
    class: 
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi
queuemanager:
  name: qm1
license: "Not Accepted"